# SPDX-License-Identifier: GPL-2.0
# Copyright 2017 NXP

include $(RTE_SDK)/mk/rte.vars.mk

DIRS-$(CONFIG_RTE_EAL_IGB_UIO) += igb_uio
DIRS-$(CONFIG_RTE_KNI_KMOD) += kni
DIRS-$(CONFIG_RTE_LSXINIC_RC_KMOD) += lsxinic
DIRS-$(CONFIG_RTE_LSXINIC_RC_VDPA_KMOD) += lsxinic_vdpa

include $(RTE_SDK)/mk/rte.subdir.mk
