;
; Supported features of the 'v2x_fce' crypto driver.
;
; Refer to default.ini for the full list of available PMD features.
;
[Features]
Symmetric crypto       = Y
HW Accelerated         = Y
OOP LB  In LB  Out     = Y

;
; Supported crypto algorithms of the 'v2x_fce' crypto driver.
;
[Cipher]
AES CBC (256) = Y
AES ECB (256) = Y

;
; Supported authentication algorithms of the 'v2x_fce' crypto driver.
;
[Auth]
SHA256 HMAC  = Y
SHA384 HMAC  = Y
SHA512 HMAC  = Y

;
; Supported AEAD algorithms of the 'v2x_fce' crypto driver.
;
[AEAD]

;
; Supported Asymmetric algorithms of the 'v2x_fce' crypto driver.
;
[Asymmetric]

;
; Supported Operating systems of the 'v2x_fce' crypto driver.
;
[OS]
Linux = Y
